apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins-container
    image: jenkins/jenkins:2.60.2
    ports:
    - containerPort: 8080
    - containerPort: 50000
    volumeMounts:
      - name: test-vol
        mountPath: /var/jenkins_home
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: ebs-claim
