---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster 
  region: ap-south-1

vpc:
  id: vpc-055a9c5304d90f00d
  cidr: "172.31.0.0/16"
  subnets:
    public:
      public-one:
        id: subnet-086691ab8f71a699e
      public-two:
        id: subnet-02ca086a0b8e33abc
      public-three:
        id: subnet-00df4fd83e873954c

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    subnets:
      - public-one
  - name: ng-2
    instanceType: t3.medium
    desiredCapacity: 1
    subnets:
      - public-three
  - name: ng-3
    instanceType: t3.medium
    desiredCapacity: 1
    subnets:
      - public-two
