apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0220f121965f14523
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - ip-172-31-14-228.ap-south-1.compute.internal 
              - ip-172-31-24-5.ap-south-1.compute.internal 
              - ip-172-31-37-58.ap-south-1.compute.internal 
